version: "3"
services:
  tickets-db:
    image: mysql:latest
    container_name: tickets-db
    restart: always
    environment:
      - MYSQL_DATABASE=tickets-db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    hostname: rabbitmq-server
    ports: 
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest